apiVersion: v1
kind: Namespace
metadata:
  name: rte
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rte-config-extra
  namespace: default
data:
  config.yaml: |
    kubelet:
      topologyManagerPolicy: single-numa-node
      topologyManagerScope: container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rte-config-daemon
  namespace: default
data:
  config.yaml: |
    global:
      verbose: 6
      debug: true
    resourceMonitor:
      exposeTiming: true
      refreshNodeResources: true
    topologyExporter:
      addNRTOwnerEnable: true
      podReadinessEnable: true
